Main filter
ccondae/anycode pull request #12
Opened 2024-04-06 15:17 UTC by Jaeeun98

- [x] : banner

- [x] : filter 

- [x] : question button

2024-04-06 16:28 UTC, Yongveloper commented on package.json
> +    "@types/react": "^18.2.74",
버전을 변경한 이유를 알 수 있을까요??

2024-04-06 16:28 UTC, Yongveloper commented on src/entities/filter/ui/filter.ui.tsx
> +        </Ul>
prettier가 적용이 안 된 거 같아요!
prettier 익스텐션 설치 한번 확인해보면 좋을 것 같아요!

2024-04-06 23:45 UTC, anveloper reviewed
앞서 병합이 완료된 main 브랜치를 로컬에서 가져와 코드 충돌하는 root.page만 코드 정리했습니다.
로컬 실행하는데는 문제가 없으나 PR checks에서 실패하고 있습니다.

2024-04-07 04:26 UTC, Jaeeun98 commented on package.json
> +    "@types/react": "^18.2.74",
실수입니다,, 다시 바꿔놓을게요!

2024-04-07 04:34 UTC, XionWCFM requested changes

2024-04-07 04:34 UTC, XionWCFM commented on package-lock.json
> -        "@types/react": "^18.2.66",
🥲 의존성 버전 올려야했던 이유 PR에 명시해주면 좋을것같아요

2024-04-07 04:34 UTC, XionWCFM commented on package.json
> +    "@types/react": "^18.2.74",
헉 실수였구나

2024-04-07 04:34 UTC, XionWCFM commented on src/entities/filter/ui/filter.ui.tsx
> +export const Filter = () => {
내보내는 컴포넌트의 이름이 Filter인건 너무 광범위한 맥락을 가지고 있는 네이밍일것 같아요
이 컴포넌트가 무엇을 필터링하는지에 대한 맥락이 이름에 더 드러나는게 다른 개발자들이 이해하기 쉬울 것 같아요

2024-04-07 04:34 UTC, XionWCFM commented on src/entities/filter/ui/filter.ui.tsx
> +        </Ul>
그러내요 프리티어 없는것같아요

2024-04-07 04:42 UTC, Jaeeun98 commented on src/entities/filter/ui/filter.ui.tsx
> +        </Ul>
넵 설치했습니당

2024-04-07 04:43 UTC, Jaeeun98 commented on src/entities/filter/ui/filter.ui.tsx
> +export const Filter = () => {
넵!

2024-04-07 05:00 UTC, Yongveloper approved these changes

2024-04-07 05:02 UTC, Yongveloper approved these changes

2024-04-07 05:02 UTC, Yongveloper approved these changes

2024-04-07 05:04 UTC, Yongveloper approved these changes

2024-04-07 05:04 UTC, XionWCFM approved these changes
ㅎㅎ;; 체인지 요청한 사람이 어프로브해야 되는군요

2024-04-07 05:05 UTC, merged